use_frameworks!

platform :ios, '8.0'

target 'WYXCommon_Example' do
  pod 'WYXCommon', :path => '../'

  target 'WYXCommon_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
